# Utiliza la imagen base de Kaniko
FROM gcr.io/kaniko-project/executor:debug

# Copia el archivo de configuración de Docker con las credenciales
COPY config.json /kaniko/.docker/config.json

# Ajusta permisos si es necesario
RUN chmod 600 /kaniko/.docker/config.json