ARG VERSION

FROM node:${VERSION}-alpine

LABEL maintainer="tu_email@example.com"
LABEL Image=kaniko




WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]